# Generated by Django 5.2.6 on 2025-10-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MergeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[("xlsx", "XLSX"), ("xls", "XLS")],
                        default="xlsx",
                        max_length=10,
                        verbose_name="输出格式",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="results/",
                        verbose_name="结果文件",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "合并任务",
                "verbose_name_plural": "合并任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ColumnRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="规则名称")),
                (
                    "source_column",
                    models.CharField(max_length=100, verbose_name="源列名"),
                ),
                ("new_column", models.CharField(max_length=100, verbose_name="新列名")),
                (
                    "extraction_start",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="提取起始位置"
                    ),
                ),
                (
                    "extraction_end",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="提取结束位置"
                    ),
                ),
                (
                    "extraction_one_indexed",
                    models.BooleanField(default=True, verbose_name="使用1索引"),
                ),
                ("mappings", models.JSONField(default=list, verbose_name="映射规则")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_rule",
                        to="merger.mergetask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "列规则",
                "verbose_name_plural": "列规则",
            },
        ),
        migrations.CreateModel(
            name="CellOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.CharField(max_length=100, verbose_name="列名")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add_prefix", "添加前缀"),
                            ("add_suffix", "添加后缀"),
                            ("remove_prefix", "删除前缀"),
                            ("remove_suffix", "删除后缀"),
                            ("replace", "替换文本"),
                            ("insert_at", "指定位置插入"),
                            ("delete_at", "指定位置删除"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="值"
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="旧值(替换用)",
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="新值(替换用)",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(blank=True, null=True, verbose_name="位置"),
                ),
                (
                    "length",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="长度(删除用)"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_operations",
                        to="merger.mergetask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "单元格操作",
                "verbose_name_plural": "单元格操作",
                "ordering": ["task", "order"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/", verbose_name="文件")),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="merger.mergetask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传文件",
                "verbose_name_plural": "上传文件",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
