# Generated by Django 5.2.6 on 2025-10-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergetask",
            name="filter_columns",
            field=models.JSONField(default=list, verbose_name="过滤列列表"),
        ),
        migrations.AddField(
            model_name="mergetask",
            name="filter_mode",
            field=models.CharField(
                choices=[
                    ("none", "不过滤"),
                    ("keep", "只保留指定列"),
                    ("remove", "删除指定列"),
                ],
                default="none",
                max_length=10,
                verbose_name="列过滤模式",
            ),
        ),
    ]
