# Generated by Django 5.2.6 on 2025-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merger", "0002_mergetask_filter_columns_mergetask_filter_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergetask",
            name="output_format",
            field=models.CharField(
                choices=[
                    ("xlsx", "XLSX"),
                    ("xls", "XLS"),
                    ("csv", "CSV"),
                    ("json", "JSON"),
                ],
                default="xlsx",
                max_length=10,
                verbose_name="输出格式",
            ),
        ),
    ]
