# Generated by Django 5.2.6 on 2025-10-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merger", "0003_alter_mergetask_output_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("xlsx", "XLSX"),
                            ("xls", "XLS"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="xlsx",
                        max_length=10,
                        verbose_name="输出格式",
                    ),
                ),
                (
                    "filter_mode",
                    models.CharField(
                        choices=[
                            ("none", "不过滤"),
                            ("keep", "只保留指定列"),
                            ("remove", "删除指定列"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="列过滤模式",
                    ),
                ),
                (
                    "filter_columns",
                    models.JSONField(default=list, verbose_name="过滤列列表"),
                ),
                (
                    "column_rule_config",
                    models.JSONField(blank=True, null=True, verbose_name="列规则配置"),
                ),
                (
                    "cell_operations_config",
                    models.JSONField(default=list, verbose_name="单元格操作配置"),
                ),
                (
                    "cleaning_config",
                    models.JSONField(default=dict, verbose_name="数据清洗配置"),
                ),
                (
                    "validation_config",
                    models.JSONField(default=dict, verbose_name="数据验证配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "任务模板",
                "verbose_name_plural": "任务模板",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataCleaningRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("remove_duplicates", "删除重复行"),
                            ("fill_null", "填充空值"),
                            ("convert_type", "转换数据类型"),
                            ("trim_spaces", "去除空格"),
                            ("standardize_date", "标准化日期"),
                            ("uppercase", "转大写"),
                            ("lowercase", "转小写"),
                        ],
                        max_length=30,
                        verbose_name="清洗动作",
                    ),
                ),
                ("columns", models.JSONField(default=list, verbose_name="应用列")),
                ("parameters", models.JSONField(default=dict, verbose_name="参数")),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaning_rules",
                        to="merger.mergetask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据清洗规则",
                "verbose_name_plural": "数据清洗规则",
                "ordering": ["task", "order"],
            },
        ),
        migrations.CreateModel(
            name="DataValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.CharField(max_length=100, verbose_name="列名")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("required", "必填字段"),
                            ("type", "数据类型"),
                            ("range", "数值范围"),
                            ("length", "长度限制"),
                            ("regex", "正则表达式"),
                            ("unique", "唯一性"),
                            ("enum", "枚举值"),
                        ],
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="验证参数")),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="错误提示"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="merger.mergetask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据验证规则",
                "verbose_name_plural": "数据验证规则",
            },
        ),
        migrations.CreateModel(
            name="FilePreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headers", models.JSONField(verbose_name="列头")),
                ("sample_rows", models.JSONField(verbose_name="示例数据(前100行)")),
                ("total_rows", models.IntegerField(verbose_name="总行数")),
                ("total_columns", models.IntegerField(verbose_name="总列数")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "column_types",
                    models.JSONField(default=dict, verbose_name="列类型分析"),
                ),
                (
                    "null_counts",
                    models.JSONField(default=dict, verbose_name="空值统计"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "uploaded_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview",
                        to="merger.uploadedfile",
                        verbose_name="上传文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件预览",
                "verbose_name_plural": "文件预览",
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="验证通过"),
                ),
                ("errors", models.JSONField(default=list, verbose_name="错误列表")),
                ("warnings", models.JSONField(default=list, verbose_name="警告列表")),
                ("statistics", models.JSONField(default=dict, verbose_name="统计信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_result",
                        to="merger.mergetask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "验证结果",
                "verbose_name_plural": "验证结果",
            },
        ),
    ]
